FROM oven/bun:debian

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /shared

COPY --from=shared . .

WORKDIR /app

COPY package.json .
RUN bun install

COPY src ./src
COPY tsconfig.json .
COPY .env .

RUN bunx prisma generate

CMD ["bun", "dev"]