FROM oven/bun:debian

RUN apt-get update -y && apt-get install -y openssl

RUN apt-get update && apt-get install -y curl \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs

WORKDIR /shared

COPY --from=shared . .

WORKDIR /app

COPY package.json .
RUN bun install

COPY src ./src
COPY tsconfig.json .
COPY .env .

RUN npx prisma generate

CMD ["bun", "dev"]